### PR TITLE
Fix travis

### PR DESCRIPTION
**Pull request by hjweide**

### CODE REVIEW

**Comment by peterchenadded** [comment]
Thanks @hjweide 

I didn't see any issues with python 3.7 and i could see the workflows still build the 3.7 wheel files.

Can you try below in travis.yml

```
before_install:
  - pip install -U pip
  - pip install numpy
```

This should fix up the numpy error, which i think i saw before when i was trying to build it

cheers,

**Comment by peterchenadded** [comment]
I think update the setup.py back to python 3.6 or 3.7 as i was able to build it on my windows without any issues and each of the github workflows worked on 3.7 as well.

The travis.yml can stay as python 3.8.

**Comment by hjweide** [comment]
> I think update the setup.py back to python 3.6 or 3.7 as i was able to build it on my windows without any issues and each of the github workflows worked on 3.7 as well.
> 
> The travis.yml can stay as python 3.8.

Sounds good, let me try this

**Comment by peterchenadded** [comment]
Also can you put back below line

image

Seems without it the windows and mac builds will fail with below error

image

**Comment by hjweide** [comment]
> Also can you put back below line

I just ran into that issue. I added it to the workflow files -- seems to be working across all three platforms now. 

Do you want to try one of these?

https://test.pypi.org/project/pyastar2d/#files

**Comment by hjweide** [comment]
Published the wheels at:
https://pypi.org/project/pyastar2d/#files

I'll take a look at these tomorrow. In the meantime, please let me know if you spot anything wrong with them. Thanks for your help with this!

**Comment by peterchenadded** [comment]
Awesome, looks good.

I tested for windows 3.7 , macos3.8 and Linux 3.7 without issues.

**Comment by hjweide** [comment]
Great! Thanks for letting me know.

**Comment by peterchenadded** [comment]
I did notice the tar.gz was no longer published. If you still need that you can update below at the end of the Linux workflow

```
      run: |
        python setup.py sdist
        #python -m twine upload --repository testpypi dist/*-manylinux*.whl dist/*.tar.gz --verbose --skip-existing
        python -m twine upload dist/*-manylinux*.whl dist/*.tar.gz --verbose --skip-existing
```

Note the below two additions
1. Python command to generate the tar.gz
2. Twine to include dist/*.tar.gz for upload

**Comment by hjweide** [comment]
Good catch. Yes, it would be good to publish a source distribution. I’ll
make these changes tonight.

**Pull request closed without merging**
